server:
  port: ${PORT:8080}

spring:
  mustache.check-template-location: false
  output.ansi.enabled: DETECT
  profiles.active: @spring.profile.from.maven@
  h2:
    console.enabled: false
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false

vaadin:
  allowed-packages:
    - com.vaadin
    - org.vaadin
    - dev.hilla
    - io.sapl

logging.level:
  "[org.atmosphere]": WARN
  web: INFO